#!/bin/bash
# install service in dev container

cd /workspace

# install client in edit mode 
# with testing dependencies:
pip install -e ".[testing]"

cd database_migration

# Check if the database has been initialized and if not initialize it
alembic -c alembic.ini upgrade head
