name: Continuous Deployment

on:
  release:
    types: [published]
    
jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ghga/${{ github.event.repository.name }}
          tags: ${{ github.event.release.tag_name }}, latest
          registry: docker.io
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  update_deployment_repo:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub

    steps:
      - name: trigger update in deployment repo
        run: |
          # access token needs to be of format: <username>:<personal_access_token>
          curl -X POST https://api.github.com/repos/ghga-de/sandbox-deployment-configs/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u '${{ secrets.DEPLOYMENT_UPDATE_TOKEN }}' \
          --data '{"event_type": "new_chart_version", "client_payload": { "chart_name": "${{ github.event.repository.name }}", "new_version": "${{ github.event.release.tag_name}}" } }'