name: Static Code Analysis

on: [push, pull_request]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install mypy pylint flake8
      - name: mypy
        run: |
          mypy --show-error-codes --disable-error-code import .
      - name: pylint
        run: |
          pylint ./sandbox_storage
      - name: flake8
        run: |
          flake8 .
