"""Made drs_id unique

Revision ID: 44afb4c8003e
Revises: bbb58e66cf6f
Create Date: 2021-08-19 08:51:42.370297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44afb4c8003e"
down_revision = "bbb58e66cf6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Just in testing phase anyway, so it is okay to remove all rows
    op.execute(sa.text("DELETE FROM drs_objects;"))
    op.alter_column("drs_objects", "size", existing_type=sa.INTEGER(), nullable=False)
    op.create_unique_constraint(None, "drs_objects", ["drs_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "drs_objects", type_="unique")
    op.alter_column("drs_objects", "size", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
